subject_data_columns = [
    "subject",
    "lap",
    "start_time"
]

vehicular_data_columns = [
    "max_speed",
    "avg_speed",
    "std_speed",
    "yaw",
    "yaw_rate",
    "roll",
    "roll_rate",
    "pitch",
    "pitch_rate",
    "lat_acce",
    "long_acce",
    "vert_acce",
    "avg_acce_pedal_pos",
    "std_acce_pedal_pos",
    "avg_steer_angle",
    "std_steer_angle"
]

neurophysiological_data_columns = [
    "hr",
    "hrv_lf",
    "hrv_hf",
    "hrv_lfhf_ratio",
    "gsr_tonic",
    "gsr_phasic",
    "gsr_peaks",
    "EBRmean",
    "BDmean",
    "ThetaFrontal",
    "ThetaParietal",
    "AlphaFrontal",
    "AlphaParietal",
    "LowerAlphaFrontal",
    "LowerAlphaParietal",
    "UpperAlphaFrontal",
    "UpperAlphaParietal",
    "BetaFrontal",
    "BetaParietal",
    "LowerBetaFrontal",
    "LowerBetaParietal",
    "UpperBetaFrontal",
    "UpperBetaParietal"
]

event_flags_columns = [
    'straight',
    'roundabout_entry',
    'roundabout_exit',
    'zebra_crossing',
    'left_turn',
    'u_turn',
    'bypass_dummy',
    'car',
    'pedestrian',
    'traffic_light',
    'narrow_road',
    'dummy',
    'bend'
]

video_data_analysis_columns = [
    "straight",
    "roundabout_entry",
    "roundabout_exit",
    "zebra_crossing",
    "left_turn",
    "u_turn",
    "bypass_dummy",
    "car",
    "pedestrian",
    "traffic_light",
    "narrow_road",
    "dummy",
    "bend",
    "habituation",
    "traffic",
    "hurry",
    "frustration",
    "surprise",
    "risk_outcome",
    "risk_source_env",
    "risk_source_other_usr",
    "risk_source_driver",
    "risk_source_crash",
    "risk_evaluation",
    "violation_no",
    "violation_roadside_invasion",
    "violation_give_the_way",
    "violation_road_signs",
    "violation_heavy_braking",
    "violation_roadside_exit",
    "violation_slowdown",
    "emotion_na",
    "emotion_neutral",
    "emotion_surprise",
    "emotion_anger",
    "emotion_boredom",
    "emotion_fear",
    "emotion_fun",
    "gaze_na",
    "gaze_complete_expl",
    "gaze_partial_expl",
    "gaze_poor_expl",
    "distraction_na",
    "distraction_no",
    "distraction_reduced_attention",
    "distraction_speaking"
]


